ath11k: fixing compilation warnings
Below warnings are specific to 64 bit compiler and are fixed

1) drivers/net/wireless/ath/ath11k/mhi.c:273:18: error: format '%x'
   expects argument of type 'unsigned int', but argument 3 has type
   'dma_addr_t {aka long long unsigned int}' [-Werror=format=]
   ath11k_info(ab, "mhi_ctrl start addr 0x%x end addr 0x%x\n",

2) drivers/net/wireless/ath/ath11k/mhi.c:273:18: error: format
   '%x' expects argument of type 'unsigned int', but argument 4
   has type 'dma_addr_t {aka long long unsigned int}'
   [-Werror=format=]

Signed-off-by: Karthikeyan Kathirvel <kathirve@codeaurora.org>
Change-Id: I306151ca5938c8a651c6a2a68d9f201b859d43cf