ath11k: ath11k warnings are fixed
Below warnings are fixed
1) drivers/net/wireless/ath/ath11k/coredump.c:250:34:
	error: format '%llx' expects argument of type 'long long unsigned int',
	but argument 4 has type 'void *' [-Werror=format=]
   ath11k_dbg(ab, ATH11K_DBG_QMI, "seg vaddr is 0x%llx len is 0x%x\n",
                                  ^                              ^
2) drivers/net/wireless/ath/ath11k/coredump.c:228:6:
	error: unused variable 'i' [-Werror=unused-variable]
  int i, len, num_seg;
      ^
3) drivers/net/wireless/ath/ath11k/qmi.c:3361:21: error: format '%llx'
   expects argument of type 'long long unsigned int', but argument 3 has
   type 'long long unsigned int *' [-Werror=format=]
     ath11k_warn(ab, "WARNING etr-addr remap failed %llx\n",

4) drivers/net/wireless/ath/ath11k/mac.c:2977:1: warning: the frame
     size of 1184 bytes is larger than 1024 bytes [-Wframe-larger-than=]
        }
	^
5) drivers/net/wireless/ath/ath11k/nss.c: In function
	'ath11k_nss_update_sta_stats':include/linux/typecheck.h:11:18: error:
	comparison of distinct pointer types lacks a cast [-Werror]

6) drivers/net/wireless/ath/ath11k/nss.c:932:6: error: unused variable
	'ac' [-Werror=unused-variable]
  	int ac, tid_idx;
      ^
7) drivers/net/wireless/ath/ath11k/coredump.c:99:22: error: unused
	variable 'ab' [-Werror=unused-variable]
  	struct ath11k_base *ab = ar_pci->ab;
                      ^
8) drivers/net/wireless/ath/ath11k/mac.c:6907:22: error: unused variable
	'ab' [-Werror=unused-variable]
  	struct ath11k_base *ab = arvif->ar->ab;
                      ^

Signed-off-by: Karthikeyan Kathirvel <kathirve@codeaurora.org>
Change-Id: I520bbb5ed3c72867cfde020b77ebe12479752533